// <auto-generated />
using System;
using AllocellaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AllocellaAPI.Migrations
{
    [DbContext(typeof(AllocellaDbContext))]
    [Migration("20260214164335_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllocellaAPI.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("StartTime", "EndTime");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7170),
                            EndTime = new DateTime(2026, 2, 24, 3, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Cook",
                            RoomId = 3,
                            StartTime = new DateTime(2026, 2, 14, 7, 0, 0, 0, DateTimeKind.Utc),
                            Status = "rejected",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7172),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7180),
                            EndTime = new DateTime(2026, 2, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Communal brief with a movie shooting crew",
                            RoomId = 6,
                            StartTime = new DateTime(2026, 2, 15, 5, 0, 0, 0, DateTimeKind.Utc),
                            Status = "approved",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7181),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7187),
                            EndTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "To declare the announcement that The Holy Grail war are now publicly known",
                            RoomId = 10,
                            StartTime = new DateTime(2026, 2, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7188),
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7194),
                            EndTime = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Purpose = "Community weekly meeting",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "completed",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7195),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AllocellaAPI.Models.BookingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("BookingHistories");
                });

            modelBuilder.Entity("AllocellaAPI.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "PS",
                            Capacity = 16,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6821),
                            Floor = 5,
                            IsAvailable = true,
                            RoomName = "M-Sect Laboratorium",
                            RoomNumber = "05.13"
                        },
                        new
                        {
                            Id = 2,
                            Building = "D4",
                            Capacity = 32,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6827),
                            Floor = 2,
                            IsAvailable = true,
                            RoomName = "Agile Laboratorium",
                            RoomNumber = "C-203"
                        },
                        new
                        {
                            Id = 3,
                            Building = "D4",
                            Capacity = 16,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6831),
                            Floor = 1,
                            IsAvailable = true,
                            RoomName = "Storage",
                            RoomNumber = "A-101"
                        },
                        new
                        {
                            Id = 4,
                            Building = "D4",
                            Capacity = 32,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6834),
                            Floor = 3,
                            IsAvailable = true,
                            RoomName = "Network Laboratorium",
                            RoomNumber = "C-305"
                        },
                        new
                        {
                            Id = 5,
                            Building = "D4",
                            Capacity = 32,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7010),
                            Floor = 3,
                            IsAvailable = true,
                            RoomName = "Operating System Laboratorium",
                            RoomNumber = "C-305"
                        },
                        new
                        {
                            Id = 6,
                            Building = "D4",
                            Capacity = 32,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7015),
                            Floor = 2,
                            IsAvailable = false,
                            RoomName = "Computer Laboratorium",
                            RoomNumber = "C-205"
                        },
                        new
                        {
                            Id = 7,
                            Building = "D4",
                            Capacity = 64,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7018),
                            Floor = 2,
                            IsAvailable = true,
                            RoomName = "Classroom",
                            RoomNumber = "B-201"
                        },
                        new
                        {
                            Id = 8,
                            Building = "SAW",
                            Capacity = 128,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7022),
                            Floor = 10,
                            IsAvailable = true,
                            RoomName = "Big Classroom",
                            RoomNumber = "10.08"
                        },
                        new
                        {
                            Id = 9,
                            Building = "D3",
                            Capacity = 160,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7028),
                            Floor = 1,
                            IsAvailable = true,
                            RoomName = "Small Auditorium",
                            RoomNumber = "HH-101"
                        },
                        new
                        {
                            Id = 10,
                            Building = "PS",
                            Capacity = 204,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(7050),
                            Floor = 6,
                            IsAvailable = true,
                            RoomName = "Big Auditorium",
                            RoomNumber = "06.06"
                        });
                });

            modelBuilder.Entity("AllocellaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6317),
                            Email = "admin@allocella.com",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$Vmn4E0COpJY3LLb2p0C49uZtFY/eH8c.csaYzX0sWrCrHpSQ7SnH2",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6322),
                            Email = "eriktriayudaw@allocella.com",
                            FullName = "Erik Triayuda Wijaya",
                            PasswordHash = "$2a$11$0BV408Lcwz2bvtnHLJq2ZeSl/upyl8NHNQmhV42DxfB0AqDyqY/TS",
                            Role = "student"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6325),
                            Email = "lepine@allocella.com",
                            FullName = "Lepine Pauline",
                            PasswordHash = "$2a$11$0BV408Lcwz2bvtnHLJq2ZeSl/upyl8NHNQmhV42DxfB0AqDyqY/TS",
                            Role = "student"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6328),
                            Email = "ellen@allocella.com",
                            FullName = "Dr. Ellen Lionhart S.Tr.Kom",
                            PasswordHash = "$2a$11$OLNjLBVUMGZllQWiJLbI2OD8FDZZBFe7xPSYA.3RUH6vnVJZ2RQ2O",
                            Role = "lecturer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 43, 32, 379, DateTimeKind.Utc).AddTicks(6331),
                            Email = "robert@allocella.com",
                            FullName = "Dr. Robert Oppenheimer Ka.Boom",
                            PasswordHash = "$2a$11$OLNjLBVUMGZllQWiJLbI2OD8FDZZBFe7xPSYA.3RUH6vnVJZ2RQ2O",
                            Role = "lecturer"
                        });
                });

            modelBuilder.Entity("AllocellaAPI.Models.Booking", b =>
                {
                    b.HasOne("AllocellaAPI.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllocellaAPI.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AllocellaAPI.Models.BookingHistory", b =>
                {
                    b.HasOne("AllocellaAPI.Models.Booking", "Booking")
                        .WithMany("History")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AllocellaAPI.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("AllocellaAPI.Models.Booking", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("AllocellaAPI.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AllocellaAPI.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
