/*  
    Comments provided by @Quackeyikz,
    although this file is generated by the ASP.NET Template.

    To help understanding the purpose of the main program,
    Each line (the commented) will have it's basic explanation.
*/
using AllocellaAPI.Data;
using Microsoft.EntityFrameworkCore;
using DotNetEnv;
using AllocellaAPI.Services.Auth;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using System.Text;

// Configure your .env ENV First for it to be loaded!
Env.Load();

// Basically creates the app
var builder = WebApplication.CreateBuilder(args);

// Connection string from env (basically taking its values)
var connectionString = 
    $"Host={Environment.GetEnvironmentVariable("DB_HOST")};" +
    $"Port={Environment.GetEnvironmentVariable("DB_PORT")};" +
    $"Database={Environment.GetEnvironmentVariable("DB_NAME")};" +
    $"Username={Environment.GetEnvironmentVariable("DB_USER")};" +
    $"Password={Environment.GetEnvironmentVariable("DB_PASSWORD")};";


// Telling ASP.NET to use the DbContext
builder.Services.AddDbContext<AllocellaDbContext>(options =>
    options.UseNpgsql(connectionString));
    // options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// Registering AuthService - yes, THE "AuthService"
builder.Services.AddScoped<IAuthService, AuthService>();

// JWT
var jwtSecret = Environment.GetEnvironmentVariable("JWT_SECRET") ?? throw new InvalidOperationException("JWT_SECRET not configured");
var jwtIssuer = Environment.GetEnvironmentVariable("JWT_ISSUER") ?? "AllocellaAPI";
var jwtAudience = Environment.GetEnvironmentVariable("JWT_AUDIENCE") ?? "AllocellaClient";
var jwtExpiryHours = int.Parse(Environment.GetEnvironmentVariable("JWT_EXPIRY_HOURS") ?? "24");

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.SaveToken = true;
    options.RequireHttpsMetadata = false;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        ClockSkew = TimeSpan.Zero
    };
});

builder.Services.AddAuthorization();

// Enable the API controllers (Depedency injection)
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
// Adds Swagger documentation (API docs)
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Enables Swagger UI (Dev tools)
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

// Enables auth middleware
app.UseAuthorization();

// Maps API routes (for routing)
app.MapControllers();

// Starts the server (application runtime)
app.Run();

// Confusing, right?