/*  
    Comments provided by @Quackeyikz,
    although this file is generated by the ASP.NET Template.

    To help understanding the purpose of the main program,
    Each line (the commented) will have it's basic explanation.
*/

// Basically creates the app
var builder = WebApplication.CreateBuilder(args);

// Enable the API controllers (Depedency injection)
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
// Adds Swagger documentation (API docs)
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    // Enables Swagger UI (Dev tools)
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

// Enables auth middleware
app.UseAuthorization();

// Maps API routes (for routing)
app.MapControllers();

// Starts the server (application runtime)
app.Run();

// Confusing, right?